// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mxholbwepyzurhykoinx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_oRW5ZFLbdMrLAQN5qV_86Q_D8A8bRmF";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);